name: React CI/CD via FTP

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Build project
      run: |
        npm install
        npm run build
        
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.hagan.life
        username: deploy@hagan.life
        password: ${{ secrets.FTP_PASSWORD }}
        #local-dir: ./build/
        target_branch: ../
        build_dir: build
